### ISSUE TITLE
Feedback: RF24L01+ Version

### ISSUE THREAD

**Issue by mannkind** [hallard/NodeMCU-Gateway#1]
First, I just wanted to say thanks for creating this PCB! Second, I know that you've documented that you don't use the RF24L01+ radio, but I gave it a try anyway. Indeed, the board does work with a few footnotes:
- NodeMCU Boot Issue: When the RF24L01+ IRQ pin is connected the NodeMCU won't boot
- Board vs MySensors Pinout - Assuming MySensors is part of the reason you created the board, the pinout seems to differ from their [Wifi Gateway Example](http://www.mysensors.org/build/esp8266_gateway)
  - CE - GPIO4
  - CSN/CS - GPIO15
- The RF24L01+ really needs a small 47uF-100uF capacitors; it would be great if there was room on the board (but soldering directly to the radio is an option)

Again, thank you for your work!

**Comment by hallard** [comment]
@mannkind 
Oh thanks for testing and for your comment. Glad to see it works.
Sorry about the IRQ pin, to be honest 1st proto I made GPIO2 was connected to RFM IRQ and (CS to D15) but as RFM69 was holding the IRQ pin LOW at startup, it prevented ESP to boot, that is why I reversed IRQ and CS lines. It seems on NRF24, IRQ is HIGH at startup (which make more sense than RFM69 setting it LOW)
I should have read about mysensor wiring and do it has they use, in fact I've done it quickly for another project asked on a French  forum. anyway you can cut IRQ line (I think it's what you've done), it's not used by mysensor ;-)

Adding place for capacitor is still doable I think. I will correct this on next revision. Did you tried everything such at the ATSHA204 ? If you need more testing I'll wait before releasing new version.

Thank you for your help 

Charles

**Comment by mannkind** [comment]
I only have the basics working/tested right now -- the NodeMCU and the RF24L01+. 
I have not tried the ATSHA204 yet; according to the [mysensors example sketch](https://github.com/mysensors/Arduino/blob/development/libraries/MySensors/examples/GatewayESP8266MQTTClient/GatewayESP8266MQTTClient.ino#L55) the ATSHA204 isn't yet supported w/the ESP8266.

**Comment by hallard** [comment]
I think they will, if they do a Gateway soft, it should as sensors does ;-)

By the way, I've just released new version V1.2. For NRF Version I made changes according to your suggestions. Hope this help.
