### ISSUE TITLE
Role of D0, D1 and D2

### ISSUE THREAD

**Issue by drasko** [hallard/NodeMCU-Gateway#10]
What's the role of these diodes and do I need them if I want simplest GW with NodeMCU board?

**Comment by drasko** [comment]
Any updates on this?

**Comment by drasko** [comment]
Still no information on this?

**Comment by hallard** [comment]
Drasko,
D0, D1 and D2 are used as an OR signal, this permit to couple 3 DIOs outpout of RMF module with only one pin, and yes they are mandatory.
