### ISSUE TITLE
Reg LoRa version PCB

### ISSUE THREAD

**Issue by asprakash** [hallard/NodeMCU-Gateway#2]
Hi ,
    I kick started my LoRa module learning phase with HopeRF 92W module. I found this open source project should be very useful for learners. Since I am in India, the final cost  (PCB, Shipping, customs)of the PCB is NOT feasible. I would like to make one at my local facility. May I know can I get the gerber file to fabricate the same PCB at my end?. I also tried some softwares like KiCad & gEDA tools. I am unable to open the schematic file due to some libraries missing. Can you suggest me some tools for how to open the schematic & .brd files on Linux.

Thanks in adv,
Prakash.

**Comment by hallard** [comment]
@asprakash 
You can open the file and generate gerber with the free version of eagle cad I think
http://www.cadsoftusa.com/download-eagle/
