### ISSUE TITLE
Firmware for Gateway

### ISSUE THREAD

**Issue by palitu** [hallard/NodeMCU-Gateway#4]
What firmware do you use for the gateway?

**Comment by hallard** [comment]
@palitu 
For now I'm using custom firmware not yet released because it's really dedicated to works with ULPNode and it's under testing. It's using modified version of RadioHead Library to support RFM69 module on ESP8266
As soon all is stable it will be released.

**Comment by palitu** [comment]
Thanks, really like the idea of a rfm esp gateway. Currently o have just
piggybacked and esp onto an emontx, via  serial.  Would love to utilise the
esp gateway,b it struggling to find a decent rfm library to use on it.
