### ISSUE TITLE
nrf24l01+ and rfm69w

### ISSUE THREAD

**Issue by raspberry007** [hallard/NodeMCU-Gateway#5]
Hi,

Can I mount and use both nrf24l01+ and rfm69w? I have both networks on nrf24 and rfm69w of sensors and having a gateway 3-in-1 is very appealing to me.

Thanks
Alex

**Comment by hallard** [comment]
@alex1sh 
Well, currently it's not possible since Chip Select pin for both SPI modules (NRF and RFM) are wired to GPIO15. Only way would be 
- No IRQ and pool module registers in loop()
- cut one wiring from NSS of one module and link it to another GPIO, not really trivial...
