### ISSUE TITLE
Power issue ?

### ISSUE THREAD

**Issue by fab33** [hallard/NodeMCU-Gateway#6]
It's quite strange I loose a lot of packet with this gateway and USB 2A input on NodeMCU.
Same setup sith another gateway work fine. Did you think NodeMCU can deliver enough power ?

**Comment by hallard** [comment]
@fab33 
depends on what you power thru the on board NODEMCU 3V3 regulator ?

may be you can try to put big capacitor between 3V3 and GND (470uF or 1000uF)
