### ISSUE TITLE
Gateway v1.3 does not work with RFM95W while v1.2 worked perfectly

### ISSUE THREAD

**Issue by dlarue** [hallard/NodeMCU-Gateway#7]
We ordered a few Gateway 1.3 boards after we were given a V1.2 board and had it working.

I can not find the V1.2 schematic to see what has changed but we've had 2 people assemble the Gateway v1.3 and both cases the NodeMCU would not power up.

**Comment by dlarue** [comment]
Digging deeper it appears the NodeMCU Lora V1.2 was marked on the bottom with "NodeMCU Gateway V1.2" and not "NodeMCU Lora Gateway V1.2" as on the top.  Once the NodeMCU is installed only the bottom silkscreen is visible.  So we ordered the wrong boards and V1.3 of the non-Lora will not work.

**Comment by hallard** [comment]
@dlarue 
the old release could be found on [releases](https://github.com/hallard/NodeMCU-Gateway/releases) section, and you can see difference 
Yes there is 3 versions each time
- classic with RFM12B/RFM69
- same but with NRF24L01 chip
- the lora one for RFM95 modules

But If you want to use the lora one, I strongly recommend the WeMos (same as nodeMCU, but better and smaller) dedicated one
https://github.com/hallard/WeMos-Lora
