### ISSUE TITLE
What Firmware for GW and What for Client

### ISSUE THREAD

**Issue by drasko** [hallard/NodeMCU-Gateway#8]
Hello,
can you please put on the README.md what firmware should be used for single-channel GW - i.e. where to obtain this firmware, how to fash it, etc...

Also, I suppose that the same board can work as a LoRaWAN client, provided LMIC. Is this correct, and if yes which firmware can we use?

**Comment by hallard** [comment]
A google search on `single channel gw esp8266` should bring you exactly what you need
https://github.com/things4u/ESP-1ch-Gateway-v5.0/

This single channel firmware is comptatible with this board.

The use of LMIC if for client side (node) not GW.

Flashing and/or coding for ESP8266 board is out of the scope of this project.
